apiVersion: v1
kind: Service
metadata:
  name: justice-redact-error-page
  namespace: ${NAMESPACE}

spec:
  selector:
    app: justice-redact-error-page

  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP