apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: justice-redact-frontend
  namespace: ${NAMESPACE}
  annotations:
    # Mandatory ExternalDNS routing annotations for MoJ Cloud Platform Gatekeeper compliance
    external-dns.alpha.kubernetes.io/aws-weight: '100'
    external-dns.alpha.kubernetes.io/set-identifier: 'justice-redact-frontend-${NAMESPACE}-green'
spec:
  ingressClassName: default-non-prod
  rules:
    - host: ${NAMESPACE}.apps.live.cloud-platform.service.justice.gov.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: justice-redact-frontend
                port:
                  number: 80
