name: Manual Promotion Control

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Select target environment to promote code to'
        required: true
        options:
        - staging
        # - production # Uncomment this line when the MoJ team provisions your prod namespace

jobs:
  manual-promote:
    name: 'Promote to ${{ github.event.inputs.environment }}'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    permissions:
      id-token: write 
      contents: read  

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.ECR_REGION }}

      - name: Log into ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Build & Push Production-Ready Image
        run: |
          docker build -t $REGISTRY/$REPOSITORY:node-$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:node-$IMAGE_TAG
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}

      - name: 'Authenticate to cluster'
        run: |
          echo "${{ secrets.KUBE_CERT }}" > ca.crt
          kubectl config set-cluster ${{ secrets.KUBE_CLUSTER }} --certificate-authority=./ca.crt --server=https://${{ secrets.KUBE_CLUSTER }}
          kubectl config set-credentials deploy-user --token=${KUBE_TOKEN}
          kubectl config set-context ${{ secrets.KUBE_CLUSTER }} --cluster=${{ secrets.KUBE_CLUSTER }} --user=deploy-user --namespace=${{ secrets.KUBE_NAMESPACE }}
          kubectl config use-context ${{ secrets.KUBE_CLUSTER }}
        env:
          KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}

      - name: Deploy Selected Kustomize Overlay
        run: |
          # Dynamically point to the selected staging or production overlay directory
          cd deployments/overlays/${{ github.event.inputs.environment }}
          
          # Set the target ECR container image tag natively
          kustomize edit set image justice-redact-frontend-image:latest=${REGISTRY}/${REPOSITORY}:node-${IMAGE_TAG}
          
          # Apply the rendered environment overlay to the cluster
          kubectl apply -k .
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}